export const authTypes = {
    AUTH_STARTING: "AUTH_STARTING",
    AUTH_SUCCESS: "AUTH_SUCCESS",
    AUTH_FAIL: "AUTH_FAIL",
    AUTH_LOGOUT: "AUTH_LOGOUT"
}

export const tabsTypes = {
    ADDING_TAB: "ADDING_TAB",
    ADD_SUCCEEDED: "ADD_SUCCEEDED",
    ADD_FAILED: "ADD_FAILED",
    FETCHING_TABS: "FETCHING_TABS",
    FETCH_SUCCEEDED: "FETCH_SUCCEEDED",
    FETCH_FAILED: "FETCH_FAILED",
    DELETE_SUCCEEDED: "DELETE_SUCCEEDED",
    UPDATING_TAB: "UPDATING_TAB",
    UPDATE_SUCCEEDED: "UPDATE_SUCCEEDED",
    UPDATE_FAILED: "UPDATE_FAILED"
}